### PR TITLE
fix(ToC): don't hard-code nav height

### LINKED ISSUE #641: Changing `--sl-nav-height` potentially breaks table of contents highlighting behavior
### What version of `starlight` are you using?

latest

### What version of `astro` are you using?

latest

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Changing the `--sl-nav-height` CSS variable (potentially) breaks the `Table of Contents` highlighting behavior.
If I understand correctly, this is because the highlighting logic hard-codes the navigation height in https://github.com/withastro/starlight/blob/88edd7ddae1b378451ba222a691e10c5b54b904c/packages/starlight/components/TableOfContents/starlight-toc.ts#L72

For the minimal reproducible example, I've modified the default `--sl-nav-height` definitions to a visibly larger value, and built the Starlight docs:

- https://github.com/fk/starlight/commit/bab3314406bfff35f4cff6872a6b7d0f67858516
- https://fk-bug-nav-height-toc-highlighting--velvety-tartufo-4cb6d0.netlify.app/getting-started/

Since https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles references https://github.com/withastro/starlight/blob/main/packages/starlight/style/props.css, which lists `--sl-nav-height`, I think it should be (as) safe (as possible) to modify it.

### Link to Minimal Reproducible Example

https://fk-bug-nav-height-toc-highlighting--velvety-tartufo-4cb6d0.netlify.app/getting-started/

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by fk**
#### What kind of changes does this PR include?

- Changes to Starlight code

#### Description

- Closes #641
- This PR modifies the "Table of Contents" highlighting logic so that `header` and `#starlight__on-this-page--mobile`'s heights are read using `getBoundingClientRect` instead of hard-coding their pixel value.
- https://fk-demo-fix-nav-height-toc-highlighting--velvety-tartufo-4cb6d0.netlify.app/getting-started/ demonstrates the code in this PR. You can find the [corresponding code here](https://github.com/fk/starlight/tree/fk/demo-fix-nav-height-toc-highlighting).
- https://fk-bug-nav-height-toc-highlighting--velvety-tartufo-4cb6d0.netlify.app/getting-started/ demonstrates the current buggy behavior; [branch here](https://github.com/fk/starlight/tree/fk/bug-nav-height-toc-highlighting).

### CODE REVIEW

File: packages/starlight/components/TableOfContents/starlight-toc.ts [hunk 1]
```diff
@@ -68,8 +68,12 @@ export class StarlightTOC extends HTMLElement {
 		// Also observe direct children of `.content` to include elements before
 		// the first heading.
 		const toObserve = document.querySelectorAll('main [id], main [id] ~ *, main .content > *');
+		const getNavHeight = (nav, summary) => nav?.getBoundingClientRect().height + (smallViewport ? summary?.getBoundingClientRect().height : 0) || 0;
```
Comment (fk) [inline packages/starlight/components/TableOfContents/starlight-toc.ts:71]: 🤔 feels a bit icky

**Review by delucis — APPROVED** [review]
Thanks @fk! Went through and quickly updated this so that the recalculation runs correctly when the window resizes, but should work now (and hopefully feels less icky 😁)

**Comment by fk** [comment]
Yay! 🎉

> and hopefully feels less icky 😁

Much better! 😅
Thank you so much, @delucis! <3
