### PR TITLE
Fix sidebar highlighting when path contains non-ASCII characters

### LINKED ISSUE #1067: Sidebar highlighting and navigation buttons not working in pages with non-ascii in path
### What version of `starlight` are you using?

0.12.0

### What version of `astro` are you using?

3.5.3

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When the current page path contains non-ascii characters, the navigation buttons at the bottom of the page is missing, and the current page is not highlighted in sidebar.

image

Reproduction:

- `pnpm create astro --template starlight`
- Create a new file at `src/content/docs/reference/a中文.md` with any content
- `pnpm dev` and navigate to `http://localhost:4321/reference/a中文/`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gdrppa?file=src%2Fcontent%2Fdocs%2Freference%2Fa%E4%B8%AD%E6%96%87.md

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by Genteure**
#### What kind of changes does this PR include?

- Changes to Starlight code

#### Description

`currentPathname` comes from [`Astro.url` in `index.astro`](https://github.com/withastro/starlight/blob/60edb22374a73bc0d02dbe2e26c2566d6400a3e8/packages/starlight/index.astro#L14), which is

> A full URL object of the request URL. Equivalent to: `new URL(Astro.request.url)`

- Closes #1067

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

File: packages/starlight/utils/navigation.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ function makeLink(
 	attrs?: LinkHTMLAttributes
 ): Link {
 	if (!isAbsolute(href)) href = pathWithBase(href);
-	const isCurrent = href === ensureTrailingSlash(currentPathname);
+	const isCurrent = new URL(href, 'http://example.com').pathname === ensureTrailingSlash(currentPathname);
```
Comment (HiDeoo) [inline packages/starlight/utils/navigation.ts:138]: I think [`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) should work in this case (I haven't tested it though yet) but if it does, it may be easier to understand than using a fake base URL? Any thoughts?

```suggestion
	const isCurrent = encodeURI(href) === ensureTrailingSlash(currentPathname);
```

**Comment by kevinzunigacuellar** [comment]
Perhaps we can re-use a test suite. I was looking around and I think it could be a good fit for `basics/navigation` -> `getSidebar()`. What do you think?

https://github.com/withastro/starlight/blob/60edb22374a73bc0d02dbe2e26c2566d6400a3e8/packages/starlight/__tests__/basics/navigation.test.ts#L16

**Review by delucis — APPROVED** [review]
Thanks for the fix @Genteure!
