### PR TITLE
Fix various Expressive Code translation issues

### LINKED ISSUE #1707: Issue with translating of "Copy to clipboard" text
### What version of `starlight` are you using?

0.21.3

### What version of `astro` are you using?

4.5.14

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Vivaldi, Firefox

### Describe the Bug

I've created `i18n\root.json` with translations of Expressive Code labels in Russian.
Then, I've updated `astro.config.mjs` with this text:
```js
export default defineConfig({
  integrations: [
    starlight({
      title: 'My Docs',
      defaultLocale: 'root',
      locales: {
        root: {
          label: 'Русский',
          lang: 'ru',
        },
      },
    }),
  ],
});
```

But it does not help - there is no translation for "Copy to clipboard" button.
Then I've added `en` locale to config:
```js
locales: {
  root: {
    label: 'Русский',
    lang: 'ru',
  },
  en: {
    label: 'English',
    lang: 'en',
  },
},
```

And now I have a translation of "Copy to clipboard" text in Russian. But I do not want to have language switcher in the navbar. I want to have only Russian locale on my site. Is this a bug or a feature? :)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tqaa8v?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by HiDeoo**
#### What kind of changes does this PR include?

- Changes to Starlight code

#### Description

- Closes #1707

This PR fixes various issues with the UI strings translation in Expressive Code. I identified two issues:

- The Expressive Code `getBlockLocale()` function uses `pathToLocale()` which can return `undefined`. This function states the following:

  > If the function returns `undefined`, the default locale provided in the Expressive Code configuration is used.

  Altho, it looks like the default locale was never configured in the Expressive Code configuration.

- The translation loading mechanism for Expressive Code did not properly handle all possible configuration: monolingual, multilingual, with or without a root locale, etc.

This pull request attempts to fix these 2 issues and also add a few tests to ensure that the expected translations are properly loaded in Expressive Code as we did not have any tests for this part of the codebase.

I would love to get @hippotastic 's feedback on this PR obviously.

### CODE REVIEW

File: packages/starlight/integrations/expressive-code/translations.ts [hunk 1]
```diff
@@ -3,24 +3,44 @@ import type { StarlightConfig } from '../../types';
...
+
+/**
+ * Get the BCP-47 language tag for the given locale.
+ * @param locale Locale string or `undefined` for the root locale.
+ */
+export function localeToLang(config: StarlightConfig, locale: string | undefined): string {
+	const lang = locale ? config.locales?.[locale]?.lang : config.locales?.root?.lang;
+	const defaultLang = config.defaultLocale?.lang || config.defaultLocale?.locale;
+	return lang || defaultLang || 'en';
+}
```
Comment (delucis) [inline packages/starlight/integrations/expressive-code/translations.ts:46]: Should this maybe live in `packages/starlight/integrations/shared/`?

**Review by delucis — APPROVED** [review]
Excellent stuff — thank you @HiDeoo 🎉 

Left one comment regarding where the `localeToLang()` function lives, but this LGTM. Will let you decide whether you want to do anything with that comment before merging.

File: packages/starlight/integrations/expressive-code/translations.ts (hunk 1 above)
Comment (HiDeoo) [reply packages/starlight/integrations/expressive-code/translations.ts:46]: Oh, right, totally forgot about that file. I'll update that and merge the PR. 👍
