### PR TITLE
fix: Search ranking on merge indexes

### LINKED ISSUE #2989: Default pagefind ranking weights are not applied to meged indexes
### What version of `starlight` are you using?

0.32.2

### What version of `astro` are you using?

5.4.2

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox, Chrome

### Describe the Bug

By default, the current site have the default values ​​applied to the `ranking` property of pagefind.
But not applied to the merged indexes, and that can let them have higher scores on search while having a worst content compared to the current site.

At first I was thinking of a bug in pagefind, which led me to open this issue: https://github.com/CloudCannon/pagefind/issues/796

But after digging my browser debugger for hours I seen that the merged indexes did not have ranking values at all. I quickly add the default value to them to test it, and everything comes back to a nominal behavior.

### Link to Minimal Reproducible Example

https://github.com/CloudCannon/pagefind/issues/796

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by XREvo**
## Description

This PR:
- Closes #2989
- Set up default values to the ranking property of merged indexes in pagefind to prevent search collision research between the current site and the sites hosting the merged indexes
- This PR do not changes starlight visual

## Test

I've tested locally with 2 variants of the starlight's documentation:
1. The first variant is the one from the main branch, without any merged indexes nor any modifications
2. The second one is nearly the same as the one from the main branch, with little modifications:
    1. A markdown file changed, replacing `climate impact` by `climate exchange`
    2. And a merge index pointing to the first site on pagefind configuration

To test it I searched for `climate exchange` (the modified text) on the second site.

Before applying the fix, search shown the original site as first result, and after the fix, modified site was first in search result (due to corp. network policies I can't upload screenshot right now to prove it)

### Details

I used this script to build and serve locally the 2 variants:
```sh
#! /bin/bash

echo "Installing serve globaly"
npm i -g serve

echo "Building the documentation for port 3001"
if [ -d "dist-3001" ]; then
    rm -rf "dist-3001"
fi
pnpm build
mv dist dist-3001

echo "Changing the content of the documentation"
sed -i 's/climate impact/climate exchange/' src/content/docs/environmental-impact.md
sed -i '52i\ \t\t\tpagefind: { indexWeight: 2.0, mergeIndex: [{ bundlePath: "http://localhost:3001/pagefind/", indexWeight: 0.5, }] },' astro.config.mjs


echo "Building the documentation for port 3002"
if [ -d "dist-3002" ]; then
    rm -rf "dist-3002"
fi
pnpm build
mv dist dist-3002

echo "Serving the 2 sites"
serve -l 3001 --cors ./dist-3001 &
serve -l 3002 --cors ./dist-3002
```

### CODE REVIEW

File: packages/starlight/schemas/pagefind.ts [hunk 1]
```diff
@@ -66,8 +66,11 @@ const pagefindIndexOptionsSchema = z.object({
 	language: z.string().optional(),
 	/**
 	 * Configure how search result rankings are calculated by Pagefind.
+	 * 
+	 * We applied the default value for the merged indexes in order to have the same search
+	 * conditions on them and do not let them have a better scoring than the current site.
 	 */
```
Comment (delucis) [inline packages/starlight/schemas/pagefind.ts:72]: I’m going to move this comment out of the JSDoc block because that text is something that is displayed to users in the editor and this feels more like an internal note to Starlight developers so we know why this was done in the future.

```suggestion
	 */
	 // We apply a default value to merged indexes in order to share the same ranking for them and the current site when not set explicitly.
```

**Review by delucis — APPROVED** [review]
Thanks for the fix @XREvo! Will make one small change to the comment and add a changeset.
